name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://transfer.sh/(RECOMMENDED)'

env:
  RECOVERY_URL: https://s3.sa-east-1.amazonaws.com/blob-sa-east-1-chronu/sara/20/209f/209ff513-73eb-42b3-b15f-b24fd778ca57.bin?response-content-disposition=attachment%3B%20filename%3D%22recovery.img.lz4%22&response-content-type=&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA4DM2EY46SOWUMUP4%2F20230521%2Fsa-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230521T033353Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Signature=69262535bb77b471e5ed2700f2c12076f584a654ee72f37d08c96164286e59f0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@main

    - name: Prepare the environment
      run: |
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Fetch image from URL
      run: |
        ls
        pwd
        wget ${{github.event.inputs.RECOVERY_URL }}

    - name: Patch Process-1
      run: |
        chmod a+x script1.sh
        chmod a+x magiskboot
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod a+x script2.sh
        ./script2.sh || true
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
        mkdir output && cd output
        mv ../recovery-patched.img recovery.img
        tar cvf fastbootd-recovery.tar recovery.img

    - name: Upload Recovery
      uses: actions/upload-artifact@v3.0.0
      with:
        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.tar
        name: Patched-Recovery
